# Generated by Django 4.0.6 on 2022-08-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='plat',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
