# Generated by Django 4.0.6 on 2022-08-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0002_motor_plat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='motor',
            name='plat',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
