# Generated by Django 4.0.6 on 2022-08-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0003_alter_motor_nama_alter_motor_plat'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='motor',
            name='merk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='motor',
            name='telp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
